### ISSUE TITLE
Missing include statements for PowerPC in ec_get_cycles.c

### ISSUE THREAD

**Issue by samhatfield** [ecmwf-ifs/fiat#1]
When building fiat on Summit, I get errors relating to the `FILE` and `PATH_MAX` constants. These are defined in stdio.h and linux/limits.h so `#include` statements need to be added. This code is only compiled when `__powerpc__` is defined, hence why it probably wasn't spotted before.

**Comment by wdeconinck** [comment]
That is great Sam! And congrats for the first public issue :)
Please fork and create a pull-request to "develop" with fix.

**Comment by samhatfield** [comment]
Done! https://github.com/ecmwf-ifs/fiat/pull/2

**Comment by samhatfield** [comment]
Closed by https://github.com/ecmwf-ifs/fiat/pull/2.
