### ISSUE TITLE
Linking fails in conda environment

### ISSUE THREAD

**Issue by rolfhm** [ecmwf-ifs/fiat#5]
Hi
I tried to compile fiat in a conda environment environment using gcc-11 and gcc-12. When compiling, there is a ton of warnings about mismatch in arguments in the calls to the MPI routines. When linking, it fails and claims it can't find libgomp.so.1, libstdc++.so.6, libgfortran.so.5, libquadmath.so.0. This happens despite CMake finding the correct libgomp and libmpi in the conda environment files. using -DENABLE_MPI=OFF make no difference.

**Comment by wdeconinck** [comment]
Hi @rolfhm, since gfortran 10, it is unavoidable to have these warnings when using the MPI F77 API.
The only means to remove these warnings is to port MPL to use the MPI_F08 module. This is something we're considering (poke @marsdeno), when we get around to it.

As for libgomp, that is not OpenMPI but compiler-specific OpenMP library. I suspect nothing is wrong with MPI.
What is the cmake command used to configure?

**Comment by rolfhm** [comment]
Yes, it's not only the omp library, but also libstdc++ and libgfortran, so it is a bit of disaster. I have used the compilers to compile and run other programs without problems.

I used `cmake ..` in `fiat/build` , after exporting FC, CC, and CXX. It seems to find ecbuild and MPI on its own.

**Comment by reuterbal** [comment]
Given that `-fallow-arguments-mismatch` should automatically be set for GNU >= 10.0, I think these warnings shouldn't show up?
https://github.com/ecmwf-ifs/fiat/blob/9507e783745d59d9a3c01e72482ab52205d2dd7f/src/fiat/CMakeLists.txt#L34-L39
Makes me wonder whether something goes wrong in the compiler identification?

**Comment by marsdeno** [comment]
@reuterbal That `-fallow-arg-mismatch` option degrades compiler strictness from failing on cases of mismatch, to emitting warnings about them. So sounds like that part is working ok from OP's message.  In any case I suspect unrelated to linking issue.

**Comment by rolfhm** [comment]
Looks very similar to what I did, except I had to specify conda-forge to get gcc and gfortran 
`conda install -c conda-forge`, otherwise it did not find the package. 

Did you check which gcc it used in the installation? If I did not set CC and FC as environment variables, it used the built-in gcc/gfortran 7.5 on my laptop and compiled.

**Comment by wdeconinck** [comment]
conda-forge was added as a permanent channel beforehand, so should be the same.
And I verified  and linking happens to the Conda environment, and also verified that cmake picked up the Conda gcc, g++, gfortran
```
ldd libfiat.so
        linux-vdso.so.1 (0x00007fffe87df000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x000014802f58d000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x000014802f385000)
	libmpi_mpifh.so.40 => /perm/nawd/conda/envs/fiatenv/lib/libmpi_mpifh.so.40 (0x000014802fbba000)
	libgomp.so.1 => /perm/nawd/conda/envs/fiatenv/lib/libgomp.so.1 (0x000014802fb84000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x000014802f165000)
	libstdc++.so.6 => /perm/nawd/conda/envs/fiatenv/lib/libstdc++.so.6 (0x000014802efba000)
	libgfortran.so.5 => /perm/nawd/conda/envs/fiatenv/lib/libgfortran.so.5 (0x000014802ee11000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x000014802ea8f000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x000014802e6ca000)
	/lib64/ld-linux-x86-64.so.2 (0x000014802fa0a000)
	libmpi.so.40 => /perm/nawd/conda/envs/fiatenv/lib/./libmpi.so.40 (0x000014802fa5e000)
	libopen-pal.so.40 => /perm/nawd/conda/envs/fiatenv/lib/./libopen-pal.so.40 (0x000014802e5c3000)
	libgcc_s.so.1 => /perm/nawd/conda/envs/fiatenv/lib/libgcc_s.so.1 (0x000014802fa47000)
	libquadmath.so.0 => /perm/nawd/conda/envs/fiatenv/lib/libquadmath.so.0 (0x000014802e589000)
	libopen-rte.so.40 => /perm/nawd/conda/envs/fiatenv/lib/././libopen-rte.so.40 (0x000014802e4cd000)
	libopen-orted-mpir.so => /perm/nawd/conda/envs/fiatenv/lib/././libopen-orted-mpir.so (0x000014802fa42000)
	libutil.so.1 => /usr/lib64/libutil.so.1 (0x000014802e2c9000)
	libz.so.1 => /perm/nawd/conda/envs/fiatenv/lib/./././libz.so.1 (0x000014802e2af000)
```

**Comment by rolfhm** [comment]
And I also need to install gxx

**Comment by wdeconinck** [comment]
ecbuild itself is not searching for these, only diagnosing what CMake is using.
Following variables are set in environment for me, and should be picked up by CMake, unless overridden on command line.

```
CC=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-cc

FC=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gfortran

CXX=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-c++

CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /perm/nawd/conda/envs/fiatenv/include

CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /perm/nawd/conda/envs/fiatenv/include

FORTRANFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /perm/nawd/conda/envs/fiatenv/include

CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /perm/nawd/conda/envs/fiatenv/include

LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/perm/nawd/conda/envs/fiatenv/lib -Wl,-rpath-link,/perm/nawd/conda/envs/fiatenv/lib -L/perm/nawd/conda/envs/fiatenv/lib

LD=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ld

STRIP=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-strip

OBJCOPY=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-objcopy

RANLIB=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ranlib

OBJDUMP=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-objdump

AR=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ar

AS=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-as

READELF=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-readelf

GPROF=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gprof

ADDR2LINE=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-addr2line

CMAKE_PREFIX_PATH=/perm/nawd/conda/envs/fiatenv:/perm/nawd/conda/envs/fiatenv/x86_64-conda-linux-gnu/sysroot/usr

# I believe conda specifies this, but I did not pass this to the cmake command, so should not be necessary.
CMAKE_ARGS=-DCMAKE_AR=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/perm/nawd/conda/envs/fiatenv/bin/x86_64-conda-linux-gnu-strip

**Comment by rolfhm** [comment]
Downloading gcc_linux-64 from standard conda sources, i.e. not conda-forge seems to work better. However, the mpi package appears to be broken and can't be installed. 
I tried to compile with DENABLE_MPI=OFF, but it still fails in the linking, trying to find some library used by the built in mpi library.

**Comment by wdeconinck** [comment]
Could you do a clean build (wiping the entire build dir of fiat), and then show output of 
of "ecbuild.log" and output of `make VERBOSE=1`

**Comment by rolfhm** [comment]
The files turn out to be pretty big and this is an open repo. Can I send them on email?

**Comment by wdeconinck** [comment]
@rolfhm Can this issue be closed?

**Comment by rolfhm** [comment]
Yes. It turned out that PHYEX downloaded and installed its own version of fiat and it worked fine.
