### ISSUE TITLE
Failure in ctest fiat_test_drhook_no_output

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/fiat#6]
Running the ctests results in a failure in fiat_test_drhook_no_output:

 2/15 Test  #2: fiat_test_drhook_no_output ............***Failed    1.24 sec
Running test /home/h01/frwd/cylc-run/FiatFailure/share/build-mo-spice_gnu/fiat/tests/fiat-test-drhook-no-output ... 
/home/h03/darth/opt/bb-stack/spice_gnu-v13/bin/mpiexec -n 1 /home/h01/frwd/cylc-run/FiatFailure/share/build-mo-spice_gnu/fiat/tests/fiat-test-drhook-no-output

srun: Job step creation temporarily disabled, retrying
srun: Job step created

Test failed. Executable should have no output
CMake Error at /home/h01/frwd/cylc-run/FiatFailure/share/mo-bundle/fiat/tests/test_drhook_no_output.cmake:30 (message):
  Test failed
Call Stack (most recent call first):
  /home/h01/frwd/cylc-run/FiatFailure/share/mo-bundle/fiat/tests/test_drhook_no_output.cmake:36 (run_command)

Is there a solution to this?

**Comment by wdeconinck** [comment]
The logic for failing the test is simply checking for output:
https://github.com/ecmwf-ifs/fiat/blob/main/tests/test_drhook_no_output.cmake#L22-L27
Perhaps you could change the logic to ignore
```
srun: Job step creation temporarily disabled, retrying
srun: Job step created
```
I had however never seen this as a print of the executable before

**Comment by wdeconinck** [comment]
For information, this test is to ensure that debugging output or other print statements would not sneak in.
