### ISSUE TITLE
Tags for fiat

### ISSUE THREAD

**Issue by climbfuji** [ecmwf-ifs/fiat#9]
We've been making up our own tags ("fake tags") for fiat so that we can install it properly with spack. So far we have:
```
    version("main", branch="main", no_cache=True)
    # Defined for spack use only
    version("1.0.0", commit="1295120464c3905e5edcbb887e4921686653eab8")
```
and we'd like to add
```
    version("1.1.0", commit="9398e04fd5d00887b9598151abfa31c388e605d5")
```
but I think it would make sense if those tags were created in the repository as well. It doesn't need to be exactly those hashes and/or those tags, just something for us to work with. Of course it would be easiest for us if 1295120 became tag `1.0.0`, but we can work around other choices, too.

**Comment by climbfuji** [comment]
@wdeconinck Do you have any feedback or suggestions on creating tags for fiat? Thanks!

**Comment by wdeconinck** [comment]
Hi @climbfuji I have added tags now 🙂: 1.0.0 and 1.1.0 (containing latest changes)

**Comment by climbfuji** [comment]
Excellent, thank you very much!
